### ISSUE TITLE
Problemas al ver actividad de un perfil

### ISSUE THREAD

**Issue by augusthur** [augusthur/virtuagora#10]
Se mezclan las notificaciones con la actividad reciente al ver el perfil de un usuario. Esto pasa porque ambas tablas tiene la misma clase y jQuery selecciona ambas.
Revisar también si se están mostrando correctamente las fechas.

**Comment by guillecro** [comment]
**FIXED**
@augusthur Con el tema de la fecha.. es algo mio?
