### ISSUE TITLE
Votar te manda al inicio de pagina

### ISSUE THREAD

**Issue by EmmanuelMess** [augusthur/virtuagora#11]
En [bases para la reforma de la Constitución de Santa Fe]( http://basesparalareforma.digital/participa/public/) que usa virtuagora votar produce que la página vaya hasta arriba de todo y muestre un cartel ("se registró el voto correctamente", etc.), el cartel se debería mostrar en el lugar, es decir, sin modificar la ubicación de los elementos de la página.
En Chrome versión 56.0.2924.87 (64-bit).
Lamento los inconvenientes si este issue no es de virtuagora.

**Comment by guillecro** [comment]
Hola Ema, gracias por el reporte
Eso fue algo que notamos que le erramos a la implementacion, no solo pasa en los comentarios, es una cuestion de experiencia de usuario y fijate que lo mismo pasa si votas un comentario.
El tema es que de backend tomamos el request y luego de trabajar con la misma se vuelve a una vista con un mensaje flash (disculpa si es muy tecnico!) 
Lo que quiero decir es que deberia ser una solucion por ajax. Le erramos ahi con el tema de la implementacion de comentar y votar.
Para la version 2.0 que la estamos pensando para mitad de este año, eso tendria que estar arreglado.

**Comment by EmmanuelMess** [comment]
Gracias por tomar en cuenta mi issue, a pesar de que no tengo mucho conocimiento en el área web, entiendo.
