### ISSUE TITLE
Problemas para iniciar la aplicación. Error 500

### ISSUE THREAD

**Issue by leomartinez** [augusthur/virtuagora#12]
**Entorno:** _Debian 9_: Apache 2.4.25, PHP 7, MariaDB 10.1.23 (reemplazo de MySQL a partir de Debian 9 por temas de licenciamiento). Certificado SSL instalado para el dominio.

**Problema:** Al iniciar la aplicación luego de de la ejecución de `install.php` presenta el error 500. 

**Info:** De [1], hay un problema con **Slim** y **Twig** con error de excepción. La sugerencia es forzar la versión de **Twig** en el `composer.json` a `"1.*"` y eliminar parte del código de `Slim/Views/Twig.php`.

Con eso levanta la primera pantalla de Virtuágora pero luego no se puede acceder a las pantallas de registro, portal, etc. 

Presenta el error 404 cuando arma la URL con el formato https://www.dominio.com.ar/portal

[1] https://github.com/slimphp/Slim/issues/589

**Comment by guillecro** [comment]
Hola Leo! Como estas?
Si, este es un problema que surgio luego de compatibilidad de las dependencia de esta version de virtuagora. 

Basicamente en el `composer.json` hay que cambiar unas lineas, para que no tome la ultima release de algunas dependencias, especialmente `twig/twig` y `slim/views`. La sugerencia de eliminar `Slim/Views/Twig.php` es buena, pero ya haciendo un downgrade de `slim/views` a la version compatible con `slim/slim` y `twig/twig` deberia de andar.

Ahora en unos minutitos hago un commit con el fix al problema.
Podes probar con este nuevo composer.json.

Lo que si me llama la atencion es el error 404 que esta lanzando. ¿en la configuracion de Apache el  DocumentRoot esta apuntando a la carpeta public del proyecto, verdad? ¿Se instalaron correctamente las tablas en la BD?

**Comment by leomartinez** [comment]
Bien, espero el commit.

El `DocumentRoot` apunta al `public`.

Las tablas creadas son estas:

```
MariaDB [virtuagora]> show tables;
+----------------------+          
| Tables_in_virtuagora |          
+----------------------+          
| acciones             |          
| adminlogs            |          
| ajustes              |          
| categorias           |          
| comentario_votos     |          
| comentarios          |          
| contactos            |          
| contenidos           |          
| documento_parrafos   |          
| documento_versiones  |          
| documentos           |          
| evento_usuario       |          
| eventos              |          
| funcionarios         |          
| notificaciones       |          
| novedades            |          
| organismos           |          
| partidos             |          
| patrulla_poder       |          
| patrullas            |          
| poderes              |          
| preusuarios          |          
| problematica_votos   |          
| problematicas        |          
| propuesta_votos      |          
| propuestas           |          
| taggables            |          
| tags                 |          
| userlogs             |          
| usuarios             |          
+----------------------+          
30 rows in set (0.00 sec)         
                                  
MariaDB [virtuagora]>            
 ```

**Comment by guillecro** [comment]
Genial! Hecho el commit.

La BD parece que esta bien creada, tenia miedo que el problema sea que estaba el modo `strict` activado.

Comentame como viene la mano, si seguis teniendo 404,
En todo caso fijate si te podes dar una vuelta por el log de Apache para ver que nos estaria informando con el 404.

**Comment by leomartinez** [comment]
Todo bien con el nuevo `composer.json`. Sigo con el problema del **404** cuando entrás al dominio ves la página de intro de Virtuágora. En el log se ve que llega al directorio `assets` pero no puede encontrar el directorio `login` (que no existe) y tampoco al directorio `portal` que está dentro del directorio `views`

```
5.199.130.188 - - [09/Jul/2017:22:31:02 -0300] "GET /assets/img/shield.png HTTP/1.1" 200 8946 "https://www.comunidadsantafe.com.ar/" "Mozilla/5.0 (Windows NT 6.1; rv:52.0) Gecko/20100101 Firefox/52.0"
5.199.130.188 - - [09/Jul/2017:22:31:02 -0300] "GET /assets/img/libre.png HTTP/1.1" 200 10817 "https://www.comunidadsantafe.com.ar/" "Mozilla/5.0 (Windows NT 6.1; rv:52.0) Gecko/20100101 Firefox/52.0"
5.199.130.188 - - [09/Jul/2017:22:31:04 -0300] "GET /assets/fonts/fontawesome-webfont.woff2?v=4.3.0 HTTP/1.1" 200 57187 "https://www.comunidadsantafe.com.ar/assets/css/font-awesome.css" "Mozilla/5.0 (Windows NT 6.1; rv:52.0) Gecko/20100101 Firefox/52.0"
5.199.130.188 - - [09/Jul/2017:22:31:05 -0300] "GET /assets/img/pre-registro-bg.jpg?1467645973 HTTP/1.1" 200 403691 "https://www.comunidadsantafe.com.ar/assets/css/app.css" "Mozilla/5.0 (Windows NT 6.1; rv:52.0) Gecko/20100101 Firefox/52.0"
5.199.130.188 - - [09/Jul/2017:22:31:13 -0300] "GET /favicon.ico HTTP/1.1" 404 3582 "-" "Mozilla/5.0 (Windows NT 6.1; rv:52.0) Gecko/20100101 Firefox/52.0"


5.199.130.188 - - [09/Jul/2017:22:31:31 -0300] "GET /login HTTP/1.1" 404 3576 "https://www.comunidadsantafe.com.ar/" "Mozilla/5.0 (Windows NT 6.1; rv:52.0) Gecko/20100101 Firefox/52.0"


5.199.130.188 - - [09/Jul/2017:22:39:56 -0300] "GET /portal HTTP/1.1" 404 3577 "https://www.comunidadsantafe.com.ar/" "Mozilla/5.0 (Windows NT 6.1; rv:52.0) Gecko/20100101 Firefox/52.0"
```

**Comment by guillecro** [comment]
@leomartinez Podes confirmarme si el modulo rewrite de apache esta activado para el proyecto? Vos lo configuraste con un Virtual Host, no?
En rato te paso una config basica
@augusthur ideas?

**Comment by guillecro** [comment]
Para habilitar el modulo rewrite de Apache, en consola como sudo
 ```a2enmod rewrite```
Luego reiniciar apache con
```service apache2 restart```

-------------------------------

Este es un ejemplo de un Virtual Host basico, que deberia no darte problema (Como tenes un SSL, imagino que habra uno para :443 tambien, pero te muestro el de :80 )

```
<VirtualHost *:80>

	ServerName dominio.org
        # Si tenes un server alias, descomentá lo siguiente
	# ServerAlias subdominio.subdominio.org 
	ServerAdmin admin@dominio.org
	DocumentRoot /var/www/virtuagora/public

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

	<Directory /var/www/virtuagora/public>
	        Options Indexes FollowSymLinks
	        AllowOverride All
	        Require all granted
	</Directory>

	#Esta config es para que re-direccione a https://
	#descomentar en caso que sea asi,
	#RewriteEngine on
	#RewriteCond %{SERVER_NAME} =subdominio.dominio.org [OR]
	#RewriteCond %{SERVER_NAME} =dominio.org
	#RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>
```
Por las dudas el de :443 es casi lo mismo, pero con las configs `SSLCertificateFile` y `SSLCertificateKeyFile`

**Comment by leomartinez** [comment]
El módulo `rewrite` está habilitado.

Usé como modelo el archivo de configuración que viene como default en apache para SSL.

Tengo el mismo problema sin usar SSL.

**Comment by guillecro** [comment]
@leomartinez Voy a ver si puedo llegar a levantar una instancia similar en una Maquina Virtual y ver que puede estar pasando, la verdad que no se me ocurre que mas puede estar desconfigurado. Use el mismo codigo hace 5 dias para levantar una instancia y no tuve problemas.. asi que voy a intentar investigar un poco que puede ser que este fallando.. no se si habra un problema con el tema del ruteo en `app.php`

Mañana lo vuelvo a revisar, te mantengo al tanto.

**Comment by guillecro** [comment]
@leomartinez  otra consulta. Como tenes configurado el htaccess? esta dentro de la carpeta public?
Fijate que pasa cuando antepones index.php antes de /portal y despues del dominio.
