### ISSUE TITLE
Advertencia de contenido mixto al utilizar HTTPS

### ISSUE THREAD

**Issue by augusthur** [augusthur/virtuagora#3]
Las vistas importan algunos recursos utilizando URLs absolutas con el protocolo explicitado en HTTP, lo que hace que Firefox muestre una advertencia cuando la plataforma se ejecuta mediante HTTPS. Es cuestión de abrir la web en ambos protocolos y ver que recursos se importan solo en HTTP para cambiarles la URL. Creo que está relacionado al font-awesome.

**Comment by guillecro** [comment]
**TODO**
Se detecto esto con el tema de las fuentes. Al menos, en Firefox es lo unico que pude ver.
En public/assets/scss/app.scss tanto open sans como Lora, el import deberia de pasar de http: a https://

**Comment by guillecro** [comment]
**TODO**
Gravatar y pixhoster tambien hace un fetch por una conexion insegura.
![bug](https://cloud.githubusercontent.com/assets/8771166/15379227/66a88b88-1d41-11e6-86ff-64e2e773583f.png)

**Comment by guillecro** [comment]
@augusthur me podrias decir en que otros casos o pantallas se da lo mismo?
Hasta ahora todo lo que sea font-awesome lo hosteamos desde nuestro servidor y lo obtenemos *.virtuagora.org... estaria certificado y todo.

Luego de lo de la fuente anda todo bien.. al menos hasta donde vi.

**Comment by guillecro** [comment]
En public/assets/scss/app.scss cambien los import de las fuentes de http a https.
**Fixed**
