### ISSUE TITLE
Scroll del editor poco usable

### ISSUE THREAD

**Issue by augusthur** [augusthur/virtuagora#5]
El scroll del editor del cuerpo de los contenidos (editor wysiwyg) aumenta su tamaño automáticamente con cada salto de línea que se introduce. Este comportamiento hace casi inusable el editor al formatear texto largos, ya que la barra de herramientas deja de estar visible. Por lo tanto hay que estar constantemente "bajando y subiendo".
El editor por defecto te permitía ajustar el tamaño del editor pero en algún momento se borró esa posibilidad y se le agregó este comportamiento de auto-redimensionarse con los saltos de línea.

**Comment by guillecro** [comment]
**TODO**
En views/contenido/crear-contenido.twig quitar la opcion autoExpand del sceditor.

```
$(function() {
        $("textarea[name='cuerpo']").sceditor({
            plugins: "bbcode",
            emoticonsEnabled: false,
            toolbarExclude: "font",
            height: '300',
            width: '98%',
            id: 'editor',
            style: "{{ baseUrl() }}/assets/css/sceditor/sceditor-panel.css",
            resizeEnabled: false,
            resizeHeight: true,
//          autoExpand: true
        });
    });
```

**Comment by augusthur** [comment]
Fijate que el "resizeHeight: true," está activo pero no se muestra el control abajo a la derecha para hacer un resize manual. En algún momento eso andaba (lo juro!).

**Comment by guillecro** [comment]
Debe ser porque lo desactive por CSS. 
De todas formas: **Fixed**
