### ISSUE TITLE
No se ven comillas (y probablemente otros caracteres) en los documentos abiertos

### ISSUE THREAD

**Issue by augusthur** [augusthur/virtuagora#6]
Se ve un &quot; en vez de las comillas al ver un documento abierto.

**Comment by augusthur** [comment]
Ya está solucionado en el fork del CEUT. Se reflejará el cambio en breve acá también. El problema está en que se hace un escape de los caracteres al guardarlos en la BD, y no es necesario ya que los caracteres se escapan al mostrarse.

**Comment by guillecro** [comment]
@augusthur Oka, buenisimo. Espero con ansias el arreglo por aqui!

**Comment by guillecro** [comment]
Recordar solucionarlo en este repositorio.
